apiVersion: v1
kind: ConfigMap
metadata:
  name: google-ads-views-provider-nginx-defaultvhost
data:
  default.conf: |
    limit_req_zone $binary_remote_addr zone=login:32m rate=1r/s;

    upstream php-fpm {
      server unix:/sockets/php-fpm.sock;
    }

    server {
      listen   80;
      server_name _;

      root /sockets/public;
      index index.php;

      error_page   500 502 503 504  /error_page.html;

      add_header X-Request-ID $request_id;

      location / {
        root /sockets/public;
        try_files $uri $uri/ /index.php$is_args$args;
      }

      location ~ \.php$ {
        root /src/public;
        access_log /dev/stdout fluentd;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php-fpm;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
      }

    }
