apiVersion: v1
kind: ConfigMap

metadata:
  name: google-ads-views-provider
  namespace: default

data:
  APP_URL: "http://youtubechannelart.info"
  APP_NAME: "GAVP"
  DB_HOST: "10.49.0.2"
  DB_PORT: "3306"
  DB_DATABASE: "google_ads_views_provider_db"
  REDIS_PORT: "6379"
  REDIS_HOST: "10.241.131.220"
  REDIS_DB: "12"
  REDIS_CACHE_DB: "12"
  APP_DEBUG: "false"
  LOG_CHANNEL: "errorlog"
  LOG_LEVEL: "info"
  CACHE_DRIVER: "redis"
  SWAP_CACHE_TTL: "21600"
  QUEUE_CONNECTION: "redis"
  SESSION_DRIVER: "redis"
  SESSION_CONNECTION: "default"
  LOG_SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/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"

  #  Google cloud error reporting
  GOOGLE_APPLICATION_CREDENTIALS: "/usr/credentials/service-account"
  GAE_SERVICE: "google-ads-views-provider"
  GAE_VERSION: ""

  # External services
  SOCIAL_PROVIDER_ENDPOINT: "http://social-provider/api/v1/"
